import React, { useState } from 'react';
import { PageHeader } from '../components/layout/PageHeader';
import { cn } from '../components/layout/AppLayout';
import { AudioRecorder } from '../components/ui/AudioRecorder';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { apiClient } from '../api/client';
import { Speaker, CSBG } from '../api/types';
import { Check } from 'lucide-react';

const steps = ['Speaker Profile', 'Voice Samples', 'Knowledge Graph', 'Build & Review'];

export function Enrolment() {
  const [currentStep, setCurrentStep] = useState(0);
  const [speakerId, setSpeakerId] = useState<string | null>(null);

  return (
    <div className="flex flex-col h-full">
      <PageHeader title="Enrolment" />
      
      {/* Wizard Header */}
      <div className="px-6 py-4 border-b border-app-border bg-app-bg flex items-center justify-center shrink-0">
        <div className="flex items-center w-full max-w-3xl">
          {steps.map((step, idx) => (
            <div key={step} className="flex items-center flex-1 last:flex-none">
              <div className="flex flex-col items-start gap-1">
                <span className="mono text-[10px] text-app-text-muted">STEP {idx + 1}</span>
                <span className={cn(
                  "text-[11px] uppercase tracking-wider font-medium",
                  idx === currentStep ? "text-app-text" : (idx < currentStep ? "text-app-text-muted" : "text-app-border-strong")
                )}>{step}</span>
              </div>
              {idx < steps.length - 1 && (
                <div className="flex-1 mx-4 h-[1px] bg-app-border" />
              )}
            </div>
          ))}
        </div>
      </div>

      <div className="p-6 max-w-[1400px] w-full mx-auto flex-1 overflow-auto">
        <div className="max-w-3xl mx-auto border border-app-border bg-app-surface rounded-sm p-6">
          {currentStep === 0 && <StepProfile onNext={(id) => { setSpeakerId(id); setCurrentStep(1); }} />}
          {currentStep === 1 && <StepVoice speakerId={speakerId!} onNext={() => setCurrentStep(2)} />}
          {currentStep === 2 && <StepKnowledge speakerId={speakerId!} onNext={() => setCurrentStep(3)} />}
          {currentStep === 3 && <StepBuild speakerId={speakerId!} />}
        </div>
      </div>
    </div>
  );
}

function StepProfile({ onNext }: { onNext: (id: string) => void }) {
  const [formData, setFormData] = useState({
    displayName: '', ageRange: '20-29', gender: 'Male', dominantLanguage: 'Tamil',
    otherLanguages: '', device: 'Studio Mic', environment: 'quiet room'
  });
  const [consent, setConsent] = useState(false);
  
  const createMutation = useMutation({
    mutationFn: (data: Omit<Speaker, 'id' | 'enrolledAt' | 'utteranceCount' | 'totalDurationSec' | 'cmi' | 'iIndex' | 'matrixLanguageRatio' | 'csbgDensity'>) => 
      apiClient.createSpeaker(data),
    onSuccess: (data) => onNext(data.id)
  });

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!consent) return;
    createMutation.mutate({
      ...formData,
      otherLanguages: formData.otherLanguages.split(',').map(s => s.trim()).filter(Boolean),
      consentGiven: consent,
      dominantLanguage: formData.dominantLanguage as any
    });
  };

  return (
    <form onSubmit={handleSubmit} className="flex flex-col gap-6">
      <div className="grid grid-cols-2 gap-4">
         <label className="flex flex-col gap-1.5">
            <span className="text-[11px] uppercase tracking-wider text-app-text-muted">Speaker ID</span>
            <input type="text" disabled value="<auto-generated>" className="h-8 border border-app-border bg-app-bg px-2 mono text-app-text-muted cursor-not-allowed" />
         </label>
         <label className="flex flex-col gap-1.5">
            <span className="text-[11px] uppercase tracking-wider text-app-text-muted">Display Name</span>
            <input required type="text" value={formData.displayName} onChange={e => setFormData({...formData, displayName: e.target.value})} className="h-8 border border-app-border px-2 focus:border-app-accent focus:outline-none transition-colors" />
         </label>
         <label className="flex flex-col gap-1.5">
            <span className="text-[11px] uppercase tracking-wider text-app-text-muted">Age Range</span>
            <select value={formData.ageRange} onChange={e => setFormData({...formData, ageRange: e.target.value})} className="h-8 border border-app-border px-2 focus:border-app-accent focus:outline-none">
              <option>18-19</option><option>20-29</option><option>30-39</option><option>40-49</option><option>50-59</option><option>60+</option>
            </select>
         </label>
         <label className="flex flex-col gap-1.5">
            <span className="text-[11px] uppercase tracking-wider text-app-text-muted">Gender</span>
            <select value={formData.gender} onChange={e => setFormData({...formData, gender: e.target.value})} className="h-8 border border-app-border px-2 focus:border-app-accent focus:outline-none">
              <option>Male</option><option>Female</option><option>Other</option><option>Prefer not to say</option>
            </select>
         </label>
         <label className="flex flex-col gap-1.5">
            <span className="text-[11px] uppercase tracking-wider text-app-text-muted">Dominant Language</span>
            <select value={formData.dominantLanguage} onChange={e => setFormData({...formData, dominantLanguage: e.target.value})} className="h-8 border border-app-border px-2 focus:border-app-accent focus:outline-none">
              <option>Tamil</option><option>English</option><option>Balanced</option>
            </select>
         </label>
         <label className="flex flex-col gap-1.5">
            <span className="text-[11px] uppercase tracking-wider text-app-text-muted">Other Languages</span>
            <input type="text" placeholder="e.g. Hindi, Telugu" value={formData.otherLanguages} onChange={e => setFormData({...formData, otherLanguages: e.target.value})} className="h-8 border border-app-border px-2 focus:border-app-accent focus:outline-none transition-colors" />
         </label>
         <label className="flex flex-col gap-1.5">
            <span className="text-[11px] uppercase tracking-wider text-app-text-muted">Device Used</span>
            <select value={formData.device} onChange={e => setFormData({...formData, device: e.target.value})} className="h-8 border border-app-border px-2 focus:border-app-accent focus:outline-none">
              <option>Studio Mic</option><option>Laptop Mic</option><option>Mobile Device</option>
            </select>
         </label>
         <label className="flex flex-col gap-1.5">
            <span className="text-[11px] uppercase tracking-wider text-app-text-muted">Recording Env</span>
            <select value={formData.environment} onChange={e => setFormData({...formData, environment: e.target.value})} className="h-8 border border-app-border px-2 focus:border-app-accent focus:outline-none">
              <option>quiet room</option><option>office</option><option>outdoor</option><option>noisy</option>
            </select>
         </label>
      </div>

      <div className="border border-app-border p-4 bg-app-bg">
        <label className="flex items-start gap-3 cursor-pointer">
          <input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} className="mt-0.5 accent-app-accent" />
          <span className="text-[12px] leading-relaxed text-app-text">Speaker has given written informed consent for voice biometric collection, personal-fact collection, and anonymised corpus release.</span>
        </label>
      </div>

      <div className="flex justify-end pt-4 border-t border-app-border">
        <button type="submit" disabled={!consent || createMutation.isPending} className="h-8 px-4 bg-app-accent text-white font-medium text-[12px] disabled:opacity-50 transition-opacity">
          {createMutation.isPending ? 'Saving...' : 'Continue'}
        </button>
      </div>
    </form>
  );
}

function StepVoice({ speakerId, onNext }: { speakerId: string, onNext: () => void }) {
  const prompts = [
    { text: 'வணக்கம், நான் சென்னையில் வசிக்கிறேன்.', type: 'monolingual-ta' },
    { text: 'The quick brown fox jumps over the lazy dog.', type: 'monolingual-en' },
    { text: 'நேத்து office-la meeting romba late aachu.', type: 'code-mixed' },
    { text: 'Tomorrow I have a flight to Madurai.', type: 'monolingual-en' },
    { text: 'எனக்கு புடிச்ச சாப்பாடு chicken biryani.', type: 'code-mixed' },
    { text: '(Free speech - introduce yourself)', type: 'free-speech' },
  ];
  const [activePromptIdx, setActivePromptIdx] = useState(0);
  const [recordings, setRecordings] = useState<number[]>([]); // store durations

  const totalDuration = recordings.reduce((a, b) => a + b, 0);
  
  const handleAccept = async (blob: Blob, durationMs: number) => {
    try {
      await apiClient.uploadUtterance(speakerId, prompts[activePromptIdx].type, blob);
      setRecordings(prev => {
        const next = [...prev];
        next[activePromptIdx] = durationMs;
        return next;
      });
      if (activePromptIdx < prompts.length - 1) setActivePromptIdx(prev => prev + 1);
    } catch (e) {
      console.error(e);
    }
  };

  const allDone = recordings.length === prompts.length && !recordings.includes(0);

  return (
    <div className="flex flex-col gap-4">
      <div className="border border-app-border bg-app-bg p-3 flex justify-between items-center">
        <div className="mono text-[11px] text-app-text-muted">
          Recorded: {recordings.filter(r => r > 0).length} / {prompts.length} · 
          Total duration: {(totalDuration/1000).toFixed(1)}s · 
          Target: 15.0s
        </div>
        <div className="w-32 h-[2px] bg-app-border">
          <div className="h-full bg-app-accent" style={{width: `${Math.min(100, (totalDuration/15000)*100)}%`}} />
        </div>
      </div>

      <AudioRecorder onAccept={handleAccept} />

      <table className="w-full text-left border-collapse border border-app-border">
        <thead className="bg-app-bg">
          <tr>
            <th className="px-3 py-2 text-[11px] uppercase tracking-wider text-app-text-muted border-b border-app-border w-8">#</th>
            <th className="px-3 py-2 text-[11px] uppercase tracking-wider text-app-text-muted border-b border-app-border">Prompt Text</th>
            <th className="px-3 py-2 text-[11px] uppercase tracking-wider text-app-text-muted border-b border-app-border">Type</th>
            <th className="px-3 py-2 text-[11px] uppercase tracking-wider text-app-text-muted border-b border-app-border w-16">Status</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-app-border">
          {prompts.map((p, i) => (
            <tr key={i} className={cn(i === activePromptIdx && "bg-app-accent/5", "transition-colors")} onClick={() => setActivePromptIdx(i)}>
              <td className="px-3 py-2 mono text-app-text-muted">{i+1}</td>
              <td className={cn("px-3 py-2", i === activePromptIdx ? "font-medium" : "")}>{p.text}</td>
              <td className="px-3 py-2 mono text-app-text-muted">{p.type}</td>
              <td className="px-3 py-2">
                {recordings[i] ? <Check className="w-4 h-4 text-app-accept" /> : <div className="w-4 h-4" />}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="flex justify-end pt-4 border-t border-app-border">
        <button type="button" onClick={onNext} className="h-8 px-4 bg-app-accent text-white font-medium text-[12px]">
          Continue
        </button>
      </div>
    </div>
  );
}

function StepKnowledge({ speakerId, onNext }: { speakerId: string, onNext: () => void }) {
  const [answers, setAnswers] = useState<string[]>([]);
  // Mock triples matching UI exactly
  const triples = [
    { s: ':speaker_07', p: ':hometown', o: ':Thanjavur' },
    { s: ':speaker_07', p: ':favouriteFood', o: ':Kothu_Parotta' }
  ];

  return (
    <div className="flex flex-col gap-6">
      <div className="border border-app-border p-3 bg-app-bg text-[12px] text-app-text-muted border-l-4 border-l-app-warning">
        Notice: These facts are stored encrypted and are never included in the released corpus.
      </div>
      
      <div className="grid grid-cols-2 gap-6">
        <div className="flex flex-col gap-4 border-r border-app-border pr-6">
           <div className="flex flex-col gap-2">
              <label className="text-[13px] font-medium">Which town are you from?</label>
              <AudioRecorder onAccept={() => {}} />
           </div>
           <div className="flex flex-col gap-2">
              <label className="text-[13px] font-medium">What is your favourite food?</label>
              <AudioRecorder onAccept={() => {}} />
           </div>
        </div>
        <div>
           <div className="text-[11px] uppercase tracking-wider text-app-text-muted mb-2">Extracted Triples (Edit)</div>
           <div className="mono text-[12px] flex flex-col gap-2 bg-app-bg p-3 border border-app-border">
              {triples.map((t, i) => (
                <div key={i} className="flex items-center gap-2 group">
                  <span className="text-app-text-muted w-24">{t.s}</span>
                  <span className="text-app-accent w-32">{t.p}</span>
                  <input type="text" defaultValue={t.o} className="bg-transparent border-b border-dashed border-app-border-strong focus:outline-none focus:border-app-accent flex-1" />
                </div>
              ))}
           </div>
        </div>
      </div>

      <div className="flex justify-end pt-4 border-t border-app-border">
        <button type="button" onClick={onNext} className="h-8 px-4 bg-app-accent text-white font-medium text-[12px]">
          Continue
        </button>
      </div>
    </div>
  );
}

function StepBuild({ speakerId }: { speakerId: string }) {
  const { data, isLoading } = useQuery({
    queryKey: ['build', speakerId],
    queryFn: () => apiClient.completeEnrolment(speakerId)
  });

  return (
    <div className="flex flex-col gap-6">
      <div className="mono text-[12px] flex flex-col gap-1.5 p-4 border border-app-border bg-app-bg">
        <div className="flex items-center justify-between"><span>[✓] Transcribed 6 utterances</span><span className="text-app-text-muted">4.2s</span></div>
        <div className="flex items-center justify-between"><span>[✓] Word-level language ID (1,204 tokens)</span><span className="text-app-text-muted">2.8s</span></div>
        <div className="flex items-center justify-between"><span>[✓] Semantic class tagging</span><span className="text-app-text-muted">3.1s</span></div>
        <div className="flex items-center justify-between"><span>[✓] ECAPA-TDNN embeddings extracted</span><span className="text-app-text-muted">1.4s</span></div>
        <div className="flex items-center justify-between"><span>[✓] Code-Switch Behaviour Graph constructed</span><span className="text-app-text-muted">0.3s</span></div>
        <div className="flex items-center text-app-warning mt-2"><span>[!] Sparse data: 4 classes below threshold</span></div>
      </div>
      
      {isLoading ? (
        <div className="text-[13px] text-app-text-muted">Processing...</div>
      ) : data ? (
        <div className="grid grid-cols-4 gap-4">
          <div className="border border-app-border p-3 flex flex-col justify-center">
            <div className="text-[10px] uppercase text-app-text-muted mb-1">Code-Mixing Index (CMI)</div>
            <div className="mono text-lg">{data.csbg.cmi.toFixed(1)}</div>
          </div>
          <div className="border border-app-border p-3 flex flex-col justify-center">
            <div className="text-[10px] uppercase text-app-text-muted mb-1">Integration Index (I)</div>
            <div className="mono text-lg">{data.csbg.iIndex.toFixed(2)}</div>
          </div>
          <div className="border border-app-border p-3 flex flex-col justify-center">
            <div className="text-[10px] uppercase text-app-text-muted mb-1">Matrix Lang Ratio (TA)</div>
            <div className="mono text-lg">{data.csbg.matrixLanguageRatio.toFixed(2)}</div>
          </div>
          <div className="border border-app-border p-3 flex flex-col justify-center">
            <div className="text-[10px] uppercase text-app-text-muted mb-1">CSBG Node Density</div>
            <div className="mono text-lg">0.82</div>
          </div>
        </div>
      ) : null}

      <div className="flex justify-end pt-4 border-t border-app-border">
        <button type="button" onClick={() => window.location.href='/speakers'} className="h-8 px-4 bg-app-accent text-white font-medium text-[12px]">
          Finish & View Profile
        </button>
      </div>
    </div>
  );
}

