"""The corpus layer -- where recorded human speech enters the system.

`simulation.py` currently occupies this slot and says in its own docstring
that nothing it produces may be reported. This module is the thing that
replaces it: a manifest format for real recordings, a loader that emits the
same `list[UtteranceTokens]` shape `eval.ablation.build_trials` already
consumes, and the elicitation protocol the recordings must follow.

WHY A MANIFEST AND NOT A DIRECTORY CONVENTION
---------------------------------------------
Because the evaluation needs facts that a filename cannot carry. Which
*session* an utterance came from decides whether a trial measures
cross-session stability or the same microphone twice (§5.3). Which *device*
and *environment* it was recorded in is the fairness audit (§5.5). Which
*prompt* elicited it decides whether a null result is a property of the
speaker or of the question (§5.1.1). Encoding those in paths means every
consumer re-parses them, and the day one speaker's folder is named differently
the evaluation silently changes meaning.

THE SPLIT THAT MATTERS
----------------------
`eval.ablation` already refuses to split dev/test by trial instead of by
speaker. This module refuses the analogous mistake one level down: **enrolment
and probe speech are split by session, never by utterance.** Two utterances
from one sitting share a microphone, a room, a mood and a topic. Enrolling on
some and probing with the others measures how well the estimator memorises a
recording session, and it flatters every number downstream. `split_sessions`
holds out a whole session and reports the speakers it had to drop for lacking
a second one.

WHAT IT REFUSES TO CERTIFY
--------------------------
A manifest carries its own `Provenance` and its own annotation quality, and
`Corpus.reportability()` returns the reasons it is not publishable rather than
a bare bool. Three states are distinguished on purpose, because they fail
differently:

  - **simulated** -- speakers differ by construction; not evidence about humans;
  - **un-annotated** -- audio recorded, tagging not run; a real intermediate
    state in a collection week, and one that must not silently score as an
    empty graph;
  - **guessed annotation** -- the LID pipeline fell back for some tokens, which
    `lid.pipeline.PipelineStats.is_corpus_grade` already refuses. The same
    definition is used here rather than a second one.

Consent is enforced, not documented. A RECORDED speaker without a consent
reference makes the manifest invalid -- see §9 of the proposal and the reason
`data/` is git-ignored in its entirety.
"""

from __future__ import annotations

import json
from collections import Counter
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

from .csbg.graph import SmoothingConfig
from .csbg.ontology import (
    ELICITABLE_CLASSES,
    ONTOLOGY_VERSION,
    Language,
    SemanticClass,
)
from .csbg.tokens import Token, UtteranceTokens

#: Bump when the manifest layout changes incompatibly. A loader that finds a
#: version it does not know refuses rather than guessing, because a silently
#: mis-parsed corpus produces numbers rather than errors.
MANIFEST_VERSION = "1.0"


class Provenance(str, Enum):
    """Where a corpus's speech came from.

    This is the field that stops a simulated number reaching a paper. It is
    stored on the manifest rather than inferred, so a corpus built by
    `from_simulation` cannot be relabelled by moving files around.
    """

    RECORDED = "RECORDED"
    """Human speakers, recorded under the protocol. The only reportable kind."""

    SIMULATED = "SIMULATED"
    """Generated by `simulation.py`. Speakers differ by construction."""

    SCRIPTED = "SCRIPTED"
    """Human speakers reading authored text (`participant_scripts/`).

    The audio is real -- real voices, microphones and rooms -- so the acoustic,
    liveness and integrity branches are unaffected by this label and a
    scripted corpus measures them honestly.

    The *content* is not. A CSBG built from read speech recovers the profile
    the script author wrote, so a scripted run cannot support §5.1's claim that
    speakers have stable code-switching habits: it would be answering a
    question with its own premise. What it does support is word-level LID
    accuracy (every token's language is known, making it a labelled evaluation
    set) and whether the pipeline recovers a *planted* profile end to end --
    the negative control for §5.1, since a pipeline that cannot find a profile
    we wrote will not find one we did not.

    Kept distinct from SIMULATED because the failure modes do not overlap:
    simulated speech has no acoustics at all, scripted speech has real
    acoustics and authored words."""

    AUGMENTED = "AUGMENTED"
    """Recorded speech with signal augmentation (noise, codec, room). Usable
    for robustness rows, never for the headline EER: the augmented copies are
    not independent speakers and inflate the trial count without adding
    speakers."""

    @property
    def is_reportable(self) -> bool:
        return self is Provenance.RECORDED


class AnnotationSource(str, Enum):
    """How a token stream got its language and semantic-class tags."""

    HUMAN = "HUMAN"
    """Hand-annotated. The validation set, and the ceiling everything else is
    measured against."""

    LLM = "LLM"
    """`lid.llm` tagging pass, rules taking precedence on script evidence."""

    RULES = "RULES"
    """`lid.rules` only. Tamil script resolves; unresolved Latin tokens are
    guessed, which is exactly what `PipelineStats.is_corpus_grade` refuses."""

    SYNTHETIC = "SYNTHETIC"
    """Tags came from the generating distribution, not from a tagger."""


class Environment(str, Enum):
    """Recording condition, for the §5.5 fairness slice.

    Deliberately coarse. A free-text field would produce thirty groups of one
    and no slice large enough to compare, and `fairness_slices` drops groups
    under `min_trials` anyway.
    """

    QUIET_ROOM = "QUIET_ROOM"
    OFFICE = "OFFICE"
    CORRIDOR = "CORRIDOR"
    OUTDOOR = "OUTDOOR"


# --------------------------------------------------------------------------
# The elicitation protocol
# --------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ElicitationPrompt:
    """One question put to a speaker, and the classes it is meant to produce.

    `target_classes` is a *hypothesis about the question*, not a label on the
    answer. `coverage_report` checks it against what the speaker actually said,
    and a prompt whose targets never appear is a broken question -- which is
    worth knowing before thirty people have answered it.
    """

    prompt_id: str
    text_en: str
    text_ta: str
    target_classes: tuple[SemanticClass, ...]

    elicits_phrase: bool = True
    """False for questions answerable with a bare noun.

    §5.1.1 is the reason this field exists: the *fact* in an answer is
    stealable, and what the CSBG measures is the wrapper the speaker puts round
    it. "What is your mother's name?" answered "Lakshmi" has no wrapper and
    gives the CSBG nothing. Such a prompt is not forbidden -- it is a useful
    control -- but it must be identifiable in the results, or its null result
    will be read as a failure of the hypothesis instead of the question.
    """


#: The recording protocol. Every class in `ELICITABLE_CLASSES` must be targeted
#: by at least one prompt, asserted below -- a class nothing elicits cannot be
#: estimated, and discovering that after collection costs a recording round.
#:
#: Prompts are open questions on purpose. A closed question produces a
#: one-word answer, and §5.1.1 explains why that is the one thing the CSBG
#: cannot read.
PROTOCOL_V1: tuple[ElicitationPrompt, ...] = (
    ElicitationPrompt(
        prompt_id="p01_family",
        text_en="Tell me about the people you live with, and what they do.",
        text_ta="நீங்க யாரோட வசிக்கறீங்க, அவங்க என்ன பண்றாங்க சொல்லுங்க.",
        target_classes=(SemanticClass.KINSHIP, SemanticClass.EDU_WORK),
    ),
    ElicitationPrompt(
        prompt_id="p02_food",
        text_en="What did you eat yesterday, and who cooked it?",
        text_ta="நேத்து என்ன சாப்பிட்டீங்க, யாரு சமைச்சாங்க?",
        target_classes=(SemanticClass.FOOD, SemanticClass.KINSHIP),
    ),
    ElicitationPrompt(
        prompt_id="p03_commute",
        text_en="Describe how you get here in the morning, start to finish.",
        text_ta="காலையில இங்க எப்படி வர்றீங்கனு ஆரம்பத்துலருந்து சொல்லுங்க.",
        target_classes=(
            SemanticClass.TRANSPORT,
            SemanticClass.TIME_DATE,
            SemanticClass.PLACE_LOCAL,
        ),
    ),
    ElicitationPrompt(
        prompt_id="p04_money",
        text_en="What did you spend money on last week, and roughly how much?",
        text_ta="போன வாரம் எதுக்கு பணம் செலவழிச்சீங்க, எவ்வளவு?",
        target_classes=(
            SemanticClass.MONEY_COMMERCE,
            SemanticClass.NUMBER,
            SemanticClass.QUANTITY_MEASURE,
        ),
    ),
    ElicitationPrompt(
        prompt_id="p05_phone",
        text_en="Which apps do you use most on your phone, and what for?",
        text_ta="உங்க ஃபோன்ல எந்த ஆப்ஸ் அதிகமா யூஸ் பண்றீங்க, எதுக்கு?",
        target_classes=(SemanticClass.TECH_DIGITAL, SemanticClass.MEDIA_ENTERTAIN),
    ),
    ElicitationPrompt(
        prompt_id="p06_study",
        text_en="Walk me through a normal college day.",
        text_ta="ஒரு சாதாரண காலேஜ் நாள் எப்படி இருக்கும் சொல்லுங்க.",
        target_classes=(
            SemanticClass.EDU_WORK,
            SemanticClass.TIME_DATE,
            SemanticClass.PLACE_LOCAL,
        ),
    ),
    ElicitationPrompt(
        prompt_id="p07_festival",
        text_en="How is Pongal celebrated in your house?",
        text_ta="உங்க வீட்ல பொங்கல் எப்படி கொண்டாடுவீங்க?",
        target_classes=(SemanticClass.RELIGION_FESTIVAL, SemanticClass.FOOD),
    ),
    ElicitationPrompt(
        prompt_id="p08_travel",
        text_en="Which places outside India would you like to see, and why?",
        text_ta="இந்தியாவுக்கு வெளிய எந்த இடங்கள பார்க்கணும்னு இருக்கு, ஏன்?",
        target_classes=(SemanticClass.PLACE_GLOBAL, SemanticClass.TRANSPORT),
    ),
    ElicitationPrompt(
        prompt_id="p09_film",
        text_en="Tell me about the last film or series you watched.",
        text_ta="கடைசியா பாத்த படம் அல்லது சீரிஸ் பத்தி சொல்லுங்க.",
        target_classes=(SemanticClass.MEDIA_ENTERTAIN, SemanticClass.EMOTION_STATE),
    ),
    ElicitationPrompt(
        prompt_id="p10_numbers",
        text_en="Read these out: your year of birth, then a price, then a time.",
        text_ta="இதை படிங்க: பிறந்த வருஷம், அப்புறம் ஒரு விலை, அப்புறம் ஒரு நேரம்.",
        target_classes=(
            SemanticClass.NUMBER,
            SemanticClass.TIME_DATE,
            SemanticClass.MONEY_COMMERCE,
        ),
    ),
    ElicitationPrompt(
        prompt_id="p11_health",
        text_en="What do you do when you fall sick?",
        text_ta="உடம்பு சரியில்லைனா என்ன பண்ணுவீங்க?",
        target_classes=(SemanticClass.BODY_HEALTH, SemanticClass.KINSHIP),
    ),
    ElicitationPrompt(
        prompt_id="p12_market",
        text_en="Describe buying vegetables at the market -- how much of what.",
        text_ta="மார்க்கெட்ல காய்கறி வாங்குறத சொல்லுங்க -- எவ்வளவு, எது.",
        target_classes=(
            SemanticClass.QUANTITY_MEASURE,
            SemanticClass.FOOD,
            SemanticClass.MONEY_COMMERCE,
        ),
    ),
    ElicitationPrompt(
        prompt_id="p13_hometown",
        text_en="Tell me about your hometown and what it is known for.",
        text_ta="உங்க ஊர் பத்தியும் அது எதுக்கு பேர் போனதுன்னும் சொல்லுங்க.",
        target_classes=(SemanticClass.PLACE_LOCAL, SemanticClass.FOOD),
    ),
    ElicitationPrompt(
        prompt_id="p14_control_name",
        text_en="What is your mother's first name?",
        text_ta="உங்க அம்மா பேர் என்ன?",
        target_classes=(SemanticClass.KINSHIP,),
        elicits_phrase=False,
    ),
)

_TARGETED = {c for p in PROTOCOL_V1 for c in p.target_classes}
assert set(ELICITABLE_CLASSES) <= _TARGETED, (
    "PROTOCOL_V1 does not elicit: "
    f"{sorted(c.value for c in set(ELICITABLE_CLASSES) - _TARGETED)}"
)

PROMPTS_BY_ID: dict[str, ElicitationPrompt] = {p.prompt_id: p for p in PROTOCOL_V1}


# --------------------------------------------------------------------------
# Records
# --------------------------------------------------------------------------


@dataclass(slots=True)
class SpeakerRecord:
    """One consenting speaker.

    `speaker_id` is a pseudonym and nothing here is a direct identifier. The
    link from pseudonym to person lives in the consent file, off this
    repository and outside `data/`, which is what makes a deletion request
    executable: destroy the link and the recordings and the manifest row
    becomes an orphan rather than a person.
    """

    speaker_id: str
    consent_ref: str = ""
    """Reference into the signed-consent register. Required when the corpus is
    RECORDED; `validate` fails without it."""

    gender: str = ""
    age_band: str = ""
    dominant_language: str = ""
    """Self-reported TA / EN / balanced. The §5.5 slice that most directly
    tests whether a VoxCeleb-trained embedding is fair to this population."""

    script_id: str = ""
    """Which read-speech script this speaker was given (`participant_scripts/`),
    empty for spontaneous speech.

    It is the speaker's language profile, and therefore the answer key: a
    SCRIPTED corpus is scored by asking whether the recovered CSBG matches the
    profile the script assigned, which is impossible without knowing which one
    they read. It also means a result on a scripted corpus can be inspected for
    the trivial failure -- two speakers given the same letter should *not*
    separate, and if they do, the separation is acoustic or accidental rather
    than lexical."""

    notes: str = ""

    def attributes(self) -> dict[str, str]:
        """Fairness-slice attributes, empty values dropped.

        Matches the `groups` argument of `eval.ablation.build_trials`, which
        ignores empty strings -- so an unanswered demographic question becomes
        an absent slice rather than a group named "".
        """
        return {
            k: v
            for k, v in (
                ("gender", self.gender),
                ("age_band", self.age_band),
                ("dominant_language", self.dominant_language),
            )
            if v
        }


@dataclass(slots=True)
class SessionRecord:
    """One sitting. The unit enrolment and probe speech are split on."""

    session_id: str
    speaker_id: str
    recorded_on: str = ""
    """ISO date. Cross-session stability is a claim about *time*, so a corpus
    whose sessions are twenty minutes apart cannot support §5.3 -- record the
    date and let the paper state the gap."""

    device: str = ""
    environment: Environment | None = None

    def attributes(self) -> dict[str, str]:
        return {
            k: v
            for k, v in (
                ("device", self.device),
                ("environment", self.environment.value if self.environment else ""),
            )
            if v
        }


@dataclass(slots=True)
class UtteranceRecord:
    """One answer to one prompt, with its annotation if it has been tagged.

    `tokens is None` and `tokens == []` mean different things and are kept
    distinct: the first is "not yet tagged", the second is "tagged, and the
    speaker said nothing scoreable". Collapsing them would let an untagged
    corpus build graphs sitting entirely at the smoothing prior and score
    near-chance against everything -- a system failure wearing the appearance
    of a weak result.
    """

    utterance_id: str
    session_id: str
    speaker_id: str
    prompt_id: str = ""
    audio_path: str = ""
    """Relative to the corpus root. Absolute paths break the day the corpus
    moves, and this one holds voiceprints, so it will be moved."""

    duration_sec: float = 0.0
    transcript: str = ""

    tokens: list[Token] | None = None
    annotation_source: AnnotationSource | None = None
    n_guessed_tokens: int = 0
    """Tokens the LID pipeline could not resolve and guessed. Mirrors
    `lid.pipeline.PipelineStats.fallback_guesses`; `Corpus.reportability`
    applies the same rule `PipelineStats.is_corpus_grade` does rather than
    inventing a second standard."""

    @property
    def is_annotated(self) -> bool:
        return self.tokens is not None

    def to_utterance_tokens(self) -> UtteranceTokens:
        """The shape everything downstream reads.

        Raises:
            ValueError: If the utterance has not been annotated. Returning an
                empty token list instead would silently contribute nothing to
                a CSBG while looking like a successful load.
        """
        if self.tokens is None:
            raise ValueError(
                f"utterance {self.utterance_id!r} has no annotation; "
                "run the LID pipeline before building graphs"
            )
        return UtteranceTokens(
            utterance_id=self.utterance_id,
            tokens=list(self.tokens),
            speaker_id=self.speaker_id,
            transcript=self.transcript,
        )


# --------------------------------------------------------------------------
# The corpus
# --------------------------------------------------------------------------


@dataclass(slots=True)
class Corpus:
    """A loaded manifest, plus the queries the evaluation needs."""

    name: str
    provenance: Provenance
    speakers: list[SpeakerRecord] = field(default_factory=list)
    sessions: list[SessionRecord] = field(default_factory=list)
    utterances: list[UtteranceRecord] = field(default_factory=list)
    root: Path | None = None
    ontology_version: str = ONTOLOGY_VERSION
    protocol_version: str = "v1"
    manifest_version: str = MANIFEST_VERSION
    notes: str = ""

    # ------------------------------------------------------------- indexes

    def speaker(self, speaker_id: str) -> SpeakerRecord | None:
        return next((s for s in self.speakers if s.speaker_id == speaker_id), None)

    def session(self, session_id: str) -> SessionRecord | None:
        return next((s for s in self.sessions if s.session_id == session_id), None)

    @property
    def speaker_ids(self) -> list[str]:
        return [s.speaker_id for s in self.speakers]

    def sessions_of(self, speaker_id: str) -> list[SessionRecord]:
        """This speaker's sessions, ordered by date then id.

        Ordering is deterministic so "hold out the last session" means the same
        thing on every machine. Undated sessions sort first, which is the
        conservative placement: they end up in enrolment rather than silently
        becoming the held-out probe.
        """
        rows = [s for s in self.sessions if s.speaker_id == speaker_id]
        return sorted(rows, key=lambda s: (s.recorded_on or "", s.session_id))

    def utterances_of(
        self, speaker_id: str, *, session_id: str | None = None
    ) -> list[UtteranceRecord]:
        return [
            u
            for u in self.utterances
            if u.speaker_id == speaker_id
            and (session_id is None or u.session_id == session_id)
        ]

    def annotated(self) -> list[UtteranceRecord]:
        return [u for u in self.utterances if u.is_annotated]

    # ------------------------------------------------------------- loading

    def tokens_by_speaker(
        self, *, session_ids: Iterable[str] | None = None
    ) -> dict[str, list[UtteranceTokens]]:
        """The `dict[speaker_id, list[UtteranceTokens]]` the evaluation takes.

        Un-annotated utterances are skipped rather than raising, because a
        collection week legitimately has some; `reportability` is where that
        gets counted and objected to.

        Args:
            session_ids: Restrict to these sessions. None takes all.
        """
        wanted = set(session_ids) if session_ids is not None else None
        out: dict[str, list[UtteranceTokens]] = {}
        for u in self.utterances:
            if not u.is_annotated:
                continue
            if wanted is not None and u.session_id not in wanted:
                continue
            out.setdefault(u.speaker_id, []).append(u.to_utterance_tokens())
        return out

    def groups(self) -> dict[str, dict[str, str]]:
        """Speaker attributes for `fairness_slices`.

        Session attributes (device, environment) are folded in only when a
        speaker's sessions agree on them. A speaker recorded on two devices has
        no single device, and asserting one would put their trials in a slice
        that half of their audio contradicts.
        """
        out: dict[str, dict[str, str]] = {}
        for spk in self.speakers:
            attrs = spk.attributes()
            sessions = self.sessions_of(spk.speaker_id)
            for key in ("device", "environment"):
                values = {s.attributes().get(key, "") for s in sessions}
                values.discard("")
                if len(values) == 1:
                    attrs[key] = values.pop()
            out[spk.speaker_id] = attrs
        return out

    # ------------------------------------------------------- certification

    def reportability(self) -> list[str]:
        """Reasons this corpus may not be reported, empty if there are none.

        A list rather than a bool because the reasons are actionable and
        different: simulated speech is never fixable, missing annotation is a
        pipeline run away, and guessed tokens want an API key. Callers that
        want a bool can test emptiness; callers writing a paper want the list.
        """
        reasons: list[str] = []

        _WHY_NOT = {
            Provenance.SIMULATED: (
                "speakers differ by construction, so separating them measures "
                "the estimator, not the hypothesis"
            ),
            Provenance.SCRIPTED: (
                "speakers read authored text, so a CSBG recovers the profile the "
                "script assigned; the acoustic and integrity branches are "
                "unaffected, but no §5.1 claim about natural code-switching "
                "follows from it"
            ),
            Provenance.AUGMENTED: "augmented copies are not independent speakers",
        }
        if not self.provenance.is_reportable:
            reasons.append(
                f"provenance is {self.provenance.value}: "
                + _WHY_NOT.get(self.provenance, "not a recorded corpus")
            )

        unannotated = len(self.utterances) - len(self.annotated())
        if unannotated:
            reasons.append(
                f"{unannotated} of {len(self.utterances)} utterances are not annotated; "
                "they are skipped by the loader and contribute nothing to any graph"
            )

        guessed = sum(u.n_guessed_tokens for u in self.annotated())
        if guessed:
            reasons.append(
                f"{guessed} tokens were guessed by the LID fallback, so the "
                "annotation is not corpus-grade (see PipelineStats.is_corpus_grade)"
            )

        single = [s for s in self.speaker_ids if len(self.sessions_of(s)) < 2]
        if single:
            reasons.append(
                f"{len(single)} speakers have one session, so no cross-session "
                "trial exists for them and §5.3 cannot be computed on this corpus"
            )

        if self.ontology_version != ONTOLOGY_VERSION:
            reasons.append(
                f"annotated under ontology {self.ontology_version}, code is at "
                f"{ONTOLOGY_VERSION}; graphs across versions are not comparable"
            )

        return reasons

    def validate(self, *, check_audio: bool = False) -> list[str]:
        """Structural problems, empty if the manifest is sound.

        Separate from `reportability`: this catches a *broken* manifest,
        that one catches a *sound but unpublishable* corpus. A corpus can be
        perfectly valid and still not be evidence about anything.

        Args:
            check_audio: Also verify every `audio_path` resolves. Off by
                default because a manifest is frequently inspected on a machine
                that does not hold the recordings -- `data/` never leaves the
                one it was recorded on.
        """
        problems: list[str] = []

        if self.manifest_version != MANIFEST_VERSION:
            problems.append(
                f"manifest version {self.manifest_version!r} != {MANIFEST_VERSION!r}"
            )

        for name, ids in (
            ("speaker", [s.speaker_id for s in self.speakers]),
            ("session", [s.session_id for s in self.sessions]),
            ("utterance", [u.utterance_id for u in self.utterances]),
        ):
            duplicates = sorted({i for i, n in Counter(ids).items() if n > 1})
            if duplicates:
                problems.append(f"duplicate {name} ids: {duplicates}")

        known_speakers = set(self.speaker_ids)
        known_sessions = {s.session_id for s in self.sessions}

        for s in self.sessions:
            if s.speaker_id not in known_speakers:
                problems.append(
                    f"session {s.session_id!r} references unknown speaker {s.speaker_id!r}"
                )

        for u in self.utterances:
            if u.speaker_id not in known_speakers:
                problems.append(
                    f"utterance {u.utterance_id!r} references unknown speaker {u.speaker_id!r}"
                )
            if u.session_id not in known_sessions:
                problems.append(
                    f"utterance {u.utterance_id!r} references unknown session {u.session_id!r}"
                )
            else:
                session = self.session(u.session_id)
                if session and session.speaker_id != u.speaker_id:
                    problems.append(
                        f"utterance {u.utterance_id!r} claims speaker {u.speaker_id!r} "
                        f"but its session belongs to {session.speaker_id!r}"
                    )
            if u.prompt_id and u.prompt_id not in PROMPTS_BY_ID:
                problems.append(
                    f"utterance {u.utterance_id!r} cites unknown prompt {u.prompt_id!r}"
                )
            if u.n_guessed_tokens and not u.is_annotated:
                problems.append(
                    f"utterance {u.utterance_id!r} reports guessed tokens but has no annotation"
                )

        # Consent is a hard requirement, not a warning. See §9. It attaches to
        # every corpus whose audio came out of a human, which is RECORDED and
        # SCRIPTED both: what consent covers is the voiceprint, and a scripted
        # speaker's voice is exactly as clonable for having read invented words.
        if self.provenance in (Provenance.RECORDED, Provenance.SCRIPTED):
            missing = sorted(s.speaker_id for s in self.speakers if not s.consent_ref)
            if missing:
                problems.append(
                    f"{self.provenance.value} speakers without a consent reference: "
                    f"{missing}. Recording a voiceprint without a signed consent "
                    "record is not a data-hygiene issue, it is the reason this "
                    "corpus cannot be used at all."
                )

        if check_audio:
            root = self.root or Path()
            for u in self.utterances:
                if u.audio_path and not (root / u.audio_path).exists():
                    problems.append(
                        f"utterance {u.utterance_id!r}: missing audio {u.audio_path!r}"
                    )

        return problems

    # ------------------------------------------------------------ coverage

    def coverage(self, *, smoothing: SmoothingConfig | None = None) -> CoverageReport:
        return coverage_report(self, smoothing=smoothing)

    # --------------------------------------------------------- serialising

    def to_dict(self) -> dict[str, Any]:
        return {
            "manifest_version": self.manifest_version,
            "name": self.name,
            "provenance": self.provenance.value,
            "ontology_version": self.ontology_version,
            "protocol_version": self.protocol_version,
            "notes": self.notes,
            "speakers": [
                {
                    "speaker_id": s.speaker_id,
                    "consent_ref": s.consent_ref,
                    "gender": s.gender,
                    "age_band": s.age_band,
                    "dominant_language": s.dominant_language,
                    "script_id": s.script_id,
                    "notes": s.notes,
                }
                for s in self.speakers
            ],
            "sessions": [
                {
                    "session_id": s.session_id,
                    "speaker_id": s.speaker_id,
                    "recorded_on": s.recorded_on,
                    "device": s.device,
                    "environment": s.environment.value if s.environment else None,
                }
                for s in self.sessions
            ],
            "utterances": [
                {
                    "utterance_id": u.utterance_id,
                    "session_id": u.session_id,
                    "speaker_id": u.speaker_id,
                    "prompt_id": u.prompt_id,
                    "audio_path": u.audio_path,
                    "duration_sec": u.duration_sec,
                    "transcript": u.transcript,
                    "annotation_source": (
                        u.annotation_source.value if u.annotation_source else None
                    ),
                    "n_guessed_tokens": u.n_guessed_tokens,
                    "tokens": (
                        None
                        if u.tokens is None
                        else [
                            {
                                "text": t.text,
                                "language": t.language.value,
                                "semantic_class": t.semantic_class.value,
                                "lid_confidence": t.lid_confidence,
                                "start_ms": t.start_ms,
                                "end_ms": t.end_ms,
                            }
                            for t in u.tokens
                        ]
                    ),
                }
                for u in self.utterances
            ],
        }


# --------------------------------------------------------------------------
# Coverage
# --------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ClassCoverage:
    semantic_class: SemanticClass
    n_tokens: int
    n_speakers_with_own_evidence: int
    """Speakers with enough tokens of this class that their own observations
    outweigh the backoff prior."""


@dataclass(frozen=True, slots=True)
class PromptCoverage:
    prompt_id: str
    n_utterances: int
    mean_tokens: float
    """§5.1.1 asks for this beside every per-class result: a prompt whose mean
    answer is a couple of tokens long has no wrapper for the CSBG to read, and
    its null result says nothing about the hypothesis."""

    hit_rate: float
    """Share of this prompt's utterances containing at least one token of a
    class the prompt was written to elicit. A low value is a broken question."""


@dataclass(slots=True)
class CoverageReport:
    """Whether the recordings can actually support the analysis.

    Run this after the pilot, not after full collection. Every problem it
    names is fixed by changing the prompts and recording again, which is
    affordable at five speakers and not at thirty.
    """

    classes: list[ClassCoverage] = field(default_factory=list)
    prompts: list[PromptCoverage] = field(default_factory=list)
    total_tokens: int = 0
    total_choice_tokens: int = 0
    n_speakers: int = 0
    min_tokens_for_own_evidence: float = 0.0

    def starved_classes(self) -> list[ClassCoverage]:
        """Elicitable classes no speaker has own-evidence for.

        These contribute the backoff prior for everyone, which is identical
        across speakers and therefore carries no biometric signal at all.
        """
        return [
            c
            for c in self.classes
            if c.semantic_class in ELICITABLE_CLASSES
            and c.n_speakers_with_own_evidence == 0
        ]

    def wrapperless_prompts(self, *, min_mean_tokens: float = 5.0) -> list[PromptCoverage]:
        """Prompts producing answers too short for the CSBG to read.

        `min_mean_tokens` is not a tuned threshold: `build_trials` marks the
        CSBG branch unavailable below `min_scored_tokens=5`, so a prompt whose
        *mean* answer is under that produces unscoreable probes more often than
        not. The default tracks that constant; pass the real one if it changes.
        """
        return [
            p
            for p in self.prompts
            if p.mean_tokens < min_mean_tokens
            and PROMPTS_BY_ID.get(p.prompt_id, None) is not None
            and PROMPTS_BY_ID[p.prompt_id].elicits_phrase
        ]

    def to_markdown(self) -> str:
        lines = [
            "## Corpus coverage",
            "",
            f"{self.n_speakers} speakers | {self.total_tokens} tokens "
            f"({self.total_choice_tokens} language choices)",
            "",
            "A class needs about "
            f"{self.min_tokens_for_own_evidence:.0f} observations before a speaker's "
            "own evidence outweighs the backoff prior (SmoothingConfig.class_alpha).",
            "",
            "| Class | Tokens | Speakers with own evidence |",
            "|---|---|---|",
        ]
        lines.extend(
            f"| {c.semantic_class.value} | {c.n_tokens} | "
            f"{c.n_speakers_with_own_evidence}/{self.n_speakers} |"
            for c in self.classes
        )

        if self.prompts:
            lines += [
                "",
                "| Prompt | Utterances | Mean tokens | Target hit rate |",
                "|---|---|---|---|",
            ]
            lines.extend(
                f"| {p.prompt_id} | {p.n_utterances} | {p.mean_tokens:.1f} | "
                f"{p.hit_rate:.0%} |"
                for p in self.prompts
            )

        starved = self.starved_classes()
        if starved:
            lines += [
                "",
                "**Starved elicitable classes** -- no speaker has enough tokens for "
                "their own evidence to outweigh the prior, so these classes are "
                "identical across speakers and carry no signal:",
                "",
            ]
            lines.extend(f"- {c.semantic_class.value} ({c.n_tokens} tokens)" for c in starved)

        thin = self.wrapperless_prompts()
        if thin:
            lines += [
                "",
                "**Prompts producing answers too short to score** (§5.1.1 -- the "
                "fact is stealable, the wrapper is the biometric):",
                "",
            ]
            lines.extend(f"- {p.prompt_id} (mean {p.mean_tokens:.1f} tokens)" for p in thin)

        return "\n".join(lines)


def coverage_report(
    corpus: Corpus, *, smoothing: SmoothingConfig | None = None
) -> CoverageReport:
    """Per-class and per-prompt coverage of a corpus.

    The own-evidence threshold is read from `SmoothingConfig.class_alpha`
    rather than written here. That is deliberate, and it is the lesson of the
    two miscalibrated floors in PROJECT.md §5.1: a constant that thresholds
    another module's behaviour must be derived from that module, or it drifts
    the first time the other one is tuned.
    """
    smoothing = smoothing or SmoothingConfig()
    alpha = smoothing.class_alpha

    per_speaker_class: dict[str, Counter[SemanticClass]] = {}
    class_totals: Counter[SemanticClass] = Counter()
    prompt_lengths: dict[str, list[int]] = {}
    prompt_hits: dict[str, list[bool]] = {}
    total_tokens = 0
    total_choice = 0

    for u in corpus.annotated():
        assert u.tokens is not None  # guarded by `annotated`
        total_tokens += len(u.tokens)
        counter = per_speaker_class.setdefault(u.speaker_id, Counter())

        present: set[SemanticClass] = set()
        for tok in u.tokens:
            present.add(tok.semantic_class)
            if tok.language.is_language_choice:
                total_choice += 1
                counter[tok.semantic_class] += 1
                class_totals[tok.semantic_class] += 1

        if u.prompt_id:
            prompt_lengths.setdefault(u.prompt_id, []).append(len(u.tokens))
            prompt = PROMPTS_BY_ID.get(u.prompt_id)
            if prompt is not None:
                prompt_hits.setdefault(u.prompt_id, []).append(
                    bool(present & set(prompt.target_classes))
                )

    classes = [
        ClassCoverage(
            semantic_class=cls_,
            n_tokens=class_totals.get(cls_, 0),
            n_speakers_with_own_evidence=sum(
                1 for c in per_speaker_class.values() if c.get(cls_, 0) >= alpha
            ),
        )
        for cls_ in SemanticClass
    ]

    prompts = [
        PromptCoverage(
            prompt_id=pid,
            n_utterances=len(lengths),
            mean_tokens=sum(lengths) / len(lengths) if lengths else 0.0,
            hit_rate=(
                sum(prompt_hits.get(pid, [])) / len(prompt_hits[pid])
                if prompt_hits.get(pid)
                else 0.0
            ),
        )
        for pid, lengths in sorted(prompt_lengths.items())
    ]

    return CoverageReport(
        classes=classes,
        prompts=prompts,
        total_tokens=total_tokens,
        total_choice_tokens=total_choice,
        n_speakers=len(per_speaker_class),
        min_tokens_for_own_evidence=alpha,
    )


# --------------------------------------------------------------------------
# Enrolment / probe split
# --------------------------------------------------------------------------


@dataclass(slots=True)
class SessionSplit:
    """Enrolment and probe speech, split by session.

    `dropped_speakers` is part of the result rather than a warning on the side,
    because a split that quietly loses a third of the population changes what
    the EER is an EER *of*, and the number is needed in the paper's methods
    paragraph.
    """

    enrolment: dict[str, list[UtteranceTokens]] = field(default_factory=dict)
    probes: dict[str, list[UtteranceTokens]] = field(default_factory=dict)
    enrolment_sessions: dict[str, list[str]] = field(default_factory=dict)
    probe_sessions: dict[str, list[str]] = field(default_factory=dict)
    dropped_speakers: list[str] = field(default_factory=list)
    cross_session: bool = True

    def summary(self) -> str:
        kind = "cross-session" if self.cross_session else "within-session"
        dropped = (
            f" | dropped {len(self.dropped_speakers)} for having one session"
            if self.dropped_speakers
            else ""
        )
        return (
            f"{kind}: {len(self.enrolment)} speakers, "
            f"{sum(len(v) for v in self.enrolment.values())} enrolment / "
            f"{sum(len(v) for v in self.probes.values())} probe utterances{dropped}"
        )


def split_sessions(
    corpus: Corpus,
    *,
    n_probe_sessions: int = 1,
    allow_within_session: bool = False,
    within_session_probe_fraction: float = 0.3,
) -> SessionSplit:
    """Split each speaker's speech into enrolment and probe sets.

    **By session, never by utterance.** Two utterances from one sitting share
    a microphone, a room, a topic and a mood, so a within-session split
    measures how well the estimator memorises a recording session. The number
    that comes out is not wrong so much as answering a different question --
    and it is the more flattering one, which is why it needs an explicit
    argument to obtain.

    Speakers with too few sessions are dropped and named. Falling back to a
    within-session split for those speakers would be worse than dropping them:
    the corpus would then contain two kinds of trial scored on one scale, and
    the mixture would be invisible in the result.

    Args:
        corpus: Loaded corpus.
        n_probe_sessions: Sessions held out per speaker, taken from the most
            recent. More than one costs enrolment speech; §5.3 wants the gap
            between enrolment and probe to be as long as the corpus allows.
        allow_within_session: Permit the flattering split for speakers with a
            single session. Off by default. When on, the result is marked
            `cross_session=False` and every consumer must say so.
        within_session_probe_fraction: Trailing share of a session's utterances
            used as probes when `allow_within_session` is set.

    Returns:
        A `SessionSplit`. `enrolment` and `probes` plug straight into
        `eval.ablation.build_trials`.
    """
    if n_probe_sessions < 1:
        raise ValueError(f"n_probe_sessions must be >= 1, got {n_probe_sessions}")

    split = SessionSplit(cross_session=not allow_within_session)

    for speaker_id in corpus.speaker_ids:
        sessions = corpus.sessions_of(speaker_id)

        if len(sessions) > n_probe_sessions:
            enrol_ids = [s.session_id for s in sessions[:-n_probe_sessions]]
            probe_ids = [s.session_id for s in sessions[-n_probe_sessions:]]
            enrol = _tokens_for(corpus, speaker_id, enrol_ids)
            probe = _tokens_for(corpus, speaker_id, probe_ids)
        elif allow_within_session and sessions:
            all_ids = [s.session_id for s in sessions]
            utterances = _tokens_for(corpus, speaker_id, all_ids)
            cut = int(len(utterances) * (1.0 - within_session_probe_fraction))
            enrol, probe = utterances[:cut], utterances[cut:]
            enrol_ids = probe_ids = all_ids
        else:
            split.dropped_speakers.append(speaker_id)
            continue

        if not enrol or not probe:
            split.dropped_speakers.append(speaker_id)
            continue

        split.enrolment[speaker_id] = enrol
        split.probes[speaker_id] = probe
        split.enrolment_sessions[speaker_id] = enrol_ids
        split.probe_sessions[speaker_id] = probe_ids

    return split


def _tokens_for(
    corpus: Corpus, speaker_id: str, session_ids: Sequence[str]
) -> list[UtteranceTokens]:
    """Annotated utterances for one speaker across sessions, in manifest order."""
    wanted = set(session_ids)
    return [
        u.to_utterance_tokens()
        for u in corpus.utterances
        if u.speaker_id == speaker_id and u.session_id in wanted and u.is_annotated
    ]


# --------------------------------------------------------------------------
# Manifest I/O
# --------------------------------------------------------------------------


def load_manifest(path: str | Path) -> Corpus:
    """Read a manifest from disk.

    The corpus root is the manifest's parent directory, so `audio_path` stays
    relative and the whole tree can be moved -- which it will be, because it
    holds voiceprints and lives outside version control.

    Raises:
        ValueError: On an unknown manifest version. Guessing at an unfamiliar
            layout produces a corpus that loads and is wrong.
    """
    path = Path(path)
    data = json.loads(path.read_text(encoding="utf-8"))
    version = data.get("manifest_version", "")
    if version != MANIFEST_VERSION:
        raise ValueError(
            f"{path}: manifest version {version!r}, this code reads {MANIFEST_VERSION!r}"
        )
    return _corpus_from_dict(data, root=path.parent)


def save_manifest(corpus: Corpus, path: str | Path) -> Path:
    """Write a manifest, creating parent directories."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(corpus.to_dict(), ensure_ascii=False, indent=2), encoding="utf-8"
    )
    return path


def _corpus_from_dict(data: dict[str, Any], *, root: Path | None = None) -> Corpus:
    speakers = [
        SpeakerRecord(
            speaker_id=s["speaker_id"],
            consent_ref=s.get("consent_ref", ""),
            gender=s.get("gender", ""),
            age_band=s.get("age_band", ""),
            dominant_language=s.get("dominant_language", ""),
            script_id=s.get("script_id", ""),
            notes=s.get("notes", ""),
        )
        for s in data.get("speakers", [])
    ]
    sessions = [
        SessionRecord(
            session_id=s["session_id"],
            speaker_id=s["speaker_id"],
            recorded_on=s.get("recorded_on", ""),
            device=s.get("device", ""),
            environment=(
                Environment(s["environment"]) if s.get("environment") else None
            ),
        )
        for s in data.get("sessions", [])
    ]
    utterances = [
        UtteranceRecord(
            utterance_id=u["utterance_id"],
            session_id=u["session_id"],
            speaker_id=u["speaker_id"],
            prompt_id=u.get("prompt_id", ""),
            audio_path=u.get("audio_path", ""),
            duration_sec=float(u.get("duration_sec", 0.0)),
            transcript=u.get("transcript", ""),
            annotation_source=(
                AnnotationSource(u["annotation_source"])
                if u.get("annotation_source")
                else None
            ),
            n_guessed_tokens=int(u.get("n_guessed_tokens", 0)),
            tokens=(
                None
                if u.get("tokens") is None
                else [
                    Token(
                        text=t["text"],
                        language=Language(t["language"]),
                        semantic_class=SemanticClass(t["semantic_class"]),
                        lid_confidence=float(t.get("lid_confidence", 1.0)),
                        start_ms=int(t.get("start_ms", 0)),
                        end_ms=int(t.get("end_ms", 0)),
                    )
                    for t in u["tokens"]
                ]
            ),
        )
        for u in data.get("utterances", [])
    ]
    return Corpus(
        name=data.get("name", ""),
        provenance=Provenance(data.get("provenance", Provenance.RECORDED.value)),
        speakers=speakers,
        sessions=sessions,
        utterances=utterances,
        root=root,
        ontology_version=data.get("ontology_version", ONTOLOGY_VERSION),
        protocol_version=data.get("protocol_version", "v1"),
        manifest_version=data.get("manifest_version", MANIFEST_VERSION),
        notes=data.get("notes", ""),
    )


# --------------------------------------------------------------------------
# Simulation bridge
# --------------------------------------------------------------------------


def from_simulation(
    sim: Any,
    *,
    name: str = "simulated",
    sessions_per_speaker: int = 2,
) -> Corpus:
    """Wrap a `simulation.SimulatedCorpus` in the corpus interface.

    This exists so the corpus code path is the *only* path -- the experiment
    runner loads a `Corpus` whether or not any human has been recorded, and
    the day the recordings land nothing downstream changes except which loader
    produced the object.

    The result is stamped `Provenance.SIMULATED`, so `reportability` refuses
    it and every table built from it carries the reason. That is the point:
    the bridge makes simulated data convenient to run and impossible to
    report by accident.

    Args:
        sim: A `simulation.SimulatedCorpus`.
        name: Corpus name.
        sessions_per_speaker: How many sessions to spread the enrolment
            utterances over. The simulator has no notion of a session, so this
            is a fiction -- it makes the *plumbing* of a cross-session split
            exercisable, and nothing about the resulting speech is actually
            cross-session. Do not read a §5.3 number off it.
    """
    if sessions_per_speaker < 1:
        raise ValueError(
            f"sessions_per_speaker must be >= 1, got {sessions_per_speaker}"
        )

    corpus = Corpus(
        name=name,
        provenance=Provenance.SIMULATED,
        notes=(
            "Generated by kavach.simulation. Sessions are a fiction introduced by "
            "corpus.from_simulation so the cross-session split can be exercised; "
            "the speech behind them is i.i.d. from one profile and shows none of "
            "the drift a real second session would."
        ),
    )

    for speaker_id in sim.speaker_ids:
        corpus.speakers.append(
            SpeakerRecord(speaker_id=speaker_id, consent_ref="n/a (simulated)")
        )

        enrolment = list(sim.enrolment.get(speaker_id, []))
        chunks = _chunk(enrolment, sessions_per_speaker)
        for idx, chunk in enumerate(chunks):
            session_id = f"{speaker_id}_s{idx:02d}"
            corpus.sessions.append(
                SessionRecord(
                    session_id=session_id,
                    speaker_id=speaker_id,
                    recorded_on=f"1970-01-{idx + 1:02d}",
                    device="simulated",
                    environment=Environment.QUIET_ROOM,
                )
            )
            corpus.utterances.extend(
                _utterance_record(u, session_id, speaker_id) for u in chunk
            )

        # Trial utterances become the final session, which is what
        # `split_sessions` holds out as probes.
        trials = list(sim.trials.get(speaker_id, []))
        if trials:
            session_id = f"{speaker_id}_s{len(chunks):02d}"
            corpus.sessions.append(
                SessionRecord(
                    session_id=session_id,
                    speaker_id=speaker_id,
                    recorded_on=f"1970-01-{len(chunks) + 1:02d}",
                    device="simulated",
                    environment=Environment.QUIET_ROOM,
                )
            )
            corpus.utterances.extend(
                _utterance_record(u, session_id, speaker_id) for u in trials
            )

    return corpus


def _utterance_record(
    utt: UtteranceTokens, session_id: str, speaker_id: str
) -> UtteranceRecord:
    return UtteranceRecord(
        utterance_id=utt.utterance_id,
        session_id=session_id,
        speaker_id=speaker_id,
        transcript=utt.transcript,
        duration_sec=len(utt.tokens) * 0.3,
        tokens=list(utt.tokens),
        annotation_source=AnnotationSource.SYNTHETIC,
    )


def _chunk(items: list[UtteranceTokens], n: int) -> list[list[UtteranceTokens]]:
    """Split into `n` near-equal contiguous chunks, dropping empty ones."""
    if not items:
        return []
    n = max(1, min(n, len(items)))
    size, extra = divmod(len(items), n)
    out: list[list[UtteranceTokens]] = []
    start = 0
    for i in range(n):
        stop = start + size + (1 if i < extra else 0)
        out.append(items[start:stop])
        start = stop
    return [c for c in out if c]


__all__ = [
    "MANIFEST_VERSION",
    "PROMPTS_BY_ID",
    "PROTOCOL_V1",
    "AnnotationSource",
    "ClassCoverage",
    "Corpus",
    "CoverageReport",
    "ElicitationPrompt",
    "Environment",
    "PromptCoverage",
    "Provenance",
    "SessionRecord",
    "SessionSplit",
    "SpeakerRecord",
    "UtteranceRecord",
    "coverage_report",
    "from_simulation",
    "load_manifest",
    "save_manifest",
    "split_sessions",
]
